### ISSUE TITLE
Absolute path for `filename` option?

### ISSUE THREAD

**Issue by yyx990803** [ampedandwired/html-webpack-plugin#265] opened 2016-03-23 05:04 UTC
I am trying to generate the HTML file at a different location from other webpack built assets. However if I specify an absolute path for the `filename` option, the generated HTML file is still nested under webpack's output path. I assume this is due to how webpack interprets assets, but is there anyway to get around it?

**Comment by jantimon** [comment] 2016-03-23 05:12
duplicate of #234

**Closed by jantimon** 2016-03-23 05:12 UTC

**Comment by yyx990803** [comment] 2016-03-23 07:10
That's not quite what I want - I want to generate the HTML to a location unrelated to the webpack output path. Also, specifying a nested path in `output.filename` is a less-than-optimal solution, because then I also have to do so for all other assets such as files processed by `file-loader` and CSS extracted with `extract-text-webpack-plugin`.

It also feels "not working as expected" when you specify an absolute path and instead see it nested under another directory. In fact the fix is pretty simple, as implemented in this PR: https://github.com/ampedandwired/html-webpack-plugin/pull/266

**Comment by yussan** [comment] 2018-01-24 14:04
i think i found the solution , i need absolute path too, because i have to deploy in netlify and combine via _redirects file.

my solution : 
in webpack config. set `output.publicPath` to `/`
```
...
output: {
    filename: "app/[name]-[hash].js",
    path: "dist",
    publicPath: "/"
  },
...
```
ref : https://stackoverflow.com/questions/36122972/preserving-folder-structure-in-output-directory-with-webpack
