### ISSUE TITLE
Html-webpack-plugin (param: chunksSortMode) wrong chunks order !!!

### ISSUE THREAD

**Issue by humorHan** [ampedandwired/html-webpack-plugin#483] opened 2016-11-07 02:59 UTC
I was very happy when I started using the Html-webpack-plugin plugin, But I recently found that the sort parameter (chunksSortMode) is not very friendly.

(chunksSortMode:function) {}.
I want to insert into the HTML JS file with the specified order I, but the result is only positive or reverse. For example:
`conf.inject = 'body';`
 `conf.chunks = ['vendor', 'common']; //The order I want`
`conf.chunksSortMode = function(){ //to do some }`
However, the following results appear：

`<script src="/assets/js/common.js"></script><script src="/assets/js/vendor.js"></script>`

View source learned that the internal call sort method, so that the loss of flexibility, but also can not achieve the results of the developers also want to.

temporarily by modifying the source to achieve the effect of their own needs, the current perfect。

Don't know if the next version will change this problem. And so on.

**Comment by jantimon** [comment] 2016-11-11 08:08
Duplicate of #481

**Closed by jantimon** 2016-11-11 08:08 UTC

**Comment by humorHan** [comment] 2016-11-11 08:43
Well, maybe I'll describe some of the problems, um... I'll describe it again.
For example, I have three JS files, I want to insert in a specific order to the HTML, but by setting a variety of chunksSortMode and can not be achieved. for example: a.js b.js c.js， I want to insert the HTML to achieve the following results ：

`<script src="./b.js"></script>`
`<script src="./a.js"></script>`
`<script src="./c.js"></script></body>`
but，failed.

By looking at the source code to understand, it is possible because the source code inside the sort function, the loss of the flexibility of the parameters.
If you really can not understand it does not matter, I temporarily change the plugin source code to achieve the effect I want.
Thank you very much to answer questions!
