### ISSUE TITLE
Conflict with Jinja2 Template Engine

### ISSUE THREAD

**Issue by lifei** [ampedandwired/html-webpack-plugin#136] opened 2015-12-08 12:29 UTC
Both Jinja2 and blueimp templates using {{ }} as markers. They are conflict. There is no way to change blueimp templates's markers.

**Comment by jantimon** [comment] 2015-12-13 09:12
Have you tried the 2.x beta branch with a loader?

**Comment by jantimon** [comment] 2015-12-17 09:11
Duplicate of #137

**Closed by jantimon** 2015-12-17 09:11 UTC

**Comment by lifei** [comment] 2015-12-18 06:09
This one is different from #137 , this one is talk about markers, #137 is talk about {% extends %}

**Comment by jantimon** [comment] 2015-12-18 07:20
But the solution is the same. 1.x does not support Jinja2 please use 2.x.
