### ISSUE TITLE
questions about html-loader

### ISSUE THREAD

**Issue by honger05** [ampedandwired/html-webpack-plugin#174] opened 2016-01-16 14:25 UTC
if I specify html loader

````js
// webpack.config.js
 {
        test: /\.html$/,
        loader: 'html-loader'
 }

// and

new HtmlWebpackPlugin({
      title: 'index',
      template: 'template.html'
})
````

then `<%= %>` context don't parse

````html
// template.html
<title><%= htmlWebpackPlugin.options.title %></title>
<img src="logo.png" />
````

and I hope that the Img can be translated as base64.

If I don't specify the html-loader. then HRM will throw an error.

**Comment by jantimon** [comment] 2016-01-16 15:26
Html loader does not support underscore templates.

**Comment by honger05** [comment] 2016-01-16 16:35
Yes, I don't want use html-loader. I want use html-webpack-plugin.

I hope this plugin can deal `<img src='logo.png' />` to '<img src='base64:xxxxxxx' />'

and in the webpack-dev-server, when I edit some assets, HotModuleReplacementPlugin will work.

 HtmlWebpackPlugin also will work.

sometimes It does good work. others throw an error.

`punycode.js:530 Uncaught TypeError: webpack_require(...) is not a function`

**Comment by jantimon** [comment] 2016-01-17 07:11
Could you please try to investigate why this happens?
How can I reproduce the error?

**Comment by wandergis** [comment] 2016-01-17 16:24
I also have this problem when i edit the template.html  so the browser auto refresh(use the `webpack-dev-server`). here is my option.
```
/**
 * Created by WangMing on 15/12/29.
 */
var webpack = require('webpack');
var WebpackDevServer = require('webpack-dev-server');
var config = require('./webpack.config');
for (key in config.entry) {
  config.entry[key].unshift('webpack-dev-server/client?http://0.0.0.0:8090', "webpack/hot/dev-server");
}
config.devtool = '#source-map';
config.plugins.push(new webpack.HotModuleReplacementPlugin());
config.plugins.push(new webpack.NoErrorsPlugin());
//启动服务
var app = new WebpackDevServer(webpack(config), {
  publicPath: config.output.publicPath,
  hot: false,
  historyApiFallback: true,
  stats: {
    colors: true
  }
});
app.listen(8090, function(err, result) {
  if (err) {
    console.log(err);
  }
  console.log('Listening at http://localhost:8090');
});
```
when I edit something and press `command+s`,the browser will refresh,and sadily throw this error:
![image](https://cloud.githubusercontent.com/assets/5799374/12378477/cc0cb1a2-bd79-11e5-8f6b-48ed9bb4578c.png)

**Comment by wandergis** [comment] 2016-01-18 03:53
#### @honger05   I solved the problem in this way，but I don't know whether it is a good way.And now I can use `webpack-dev-server` without any error. You can hava a try,hope it will help you.
![image](https://cloud.githubusercontent.com/assets/5799374/12382797/fa080a5c-bdd8-11e5-8abd-c7936d417261.png)

**Comment by jantimon** [comment] 2016-01-18 14:59
Okay I looked into it but I have no idea what is going wrong here.

```
/* WEBPACK VAR INJECTION */}.call(exports, __webpack_require__(2)(module), (function() {
```

The result of `__webpack_require__(2)` is not a function and therefore `__webpack_require__(2)(module)` fails.

**Comment by jantimon** [comment] 2016-01-19 09:06
Fixed with #179

**Closed by jantimon** 2016-01-19 09:06 UTC

**Comment by yanyu0517** [comment] 2016-03-27 07:30
Have the issue was fixed? I still have the problem with version 2.14.0
I also dom't want to use html-loader, just hope the plugin can deal the `<img src=""logon.png >` to `<img src="[hash].png">`

**Comment by gilbarbara** [comment] 2016-04-22 06:27
hey @jantimon 
I'm getting this problem too while using html-loader with this plugin. I need to load the `link href` images from it but the template tags don't get parsed.

```javascript
new HtmlWebpackPlugin({
    inject: false,
    template: 'html?attrs=link:href!./index.html'
});
```

[s]

**Comment by jantimon** [comment] 2016-04-22 09:16
@gilbarbara maybe the https://github.com/jantimon/favicons-webpack-plugin might fit your needs

**Comment by airtonix** [comment] 2016-07-19 05:07
@jantimon nope, that won't solve it, because we have precompiled favicons which can't simply be generated from one source image.

we use swig to parse the html, but that doesn't result in asset references being turned into bundled assets.

**Comment by liuliangsir** [comment] 2017-02-07 02:21
```
<title><%= htmlWebpackPlugin.options.title %></title>
```
ejs syntax

if you would like to use like ejs syntax in html template
you should do that
```
<title>{%=o.htmlWebpackPlugin.options.title%}</title>
```

**Comment by zhangdingding** [comment] 2017-05-20 17:24
Has anybody got any good idea about the subject? I mean how to parse a image from `<img src="xxx.png">` to `<img src="xxx.hash.png">` **in a elegant way**?
