### ISSUE TITLE
Bluebird 3 is sending warnings to the console. 

### ISSUE THREAD

**Issue by nicksrandall** [ampedandwired/html-webpack-plugin#130] opened 2015-12-02 23:39 UTC
https://github.com/petkaantonov/bluebird/blob/master/docs/docs/new-in-bluebird-3.md#warnings

Bluebird says you have a "runaway" promise in the promise chain starting in line 19 in index.js file. 

```
Warning: a promise was created in a  handler but was not returned from it
    at Compiler.<anonymous> (/Users/nicksrandall/Desktop/dawp-test/node_modules/html-webpack-plugin/index.js:19:13)
    at Compiler.next (/Users/nicksrandall/Desktop/dawp-test/node_modules/webpack/node_modules/tapable/lib/Tapable.js:69:14)
    at /Users/nicksrandall/Desktop/dawp-test/node_modules/html-webpack-plugin/index.js:68:9
From previous event:
    at Compiler.<anonymous> (/Users/nicksrandall/Desktop/dawp-test/node_modules/html-webpack-plugin/index.js:67:15)
    at Compiler.applyPluginsAsync (/Users/nicksrandall/Desktop/dawp-test/node_modules/webpack/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.emitAssets (/Users/nicksrandall/Desktop/dawp-test/node_modules/webpack/lib/Compiler.js:226:7)
    at Watching.<anonymous> (/Users/nicksrandall/Desktop/dawp-test/node_modules/webpack/lib/Compiler.js:54:18)
    at /Users/nicksrandall/Desktop/dawp-test/node_modules/webpack/lib/Compiler.js:403:12
    at Compiler.applyPluginsAsync (/Users/nicksrandall/Desktop/dawp-test/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compiler.<anonymous> (/Users/nicksrandall/Desktop/dawp-test/node_modules/webpack/lib/Compiler.js:400:9)
    at Compilation.<anonymous> (/Users/nicksrandall/Desktop/dawp-test/node_modules/webpack/lib/Compilation.js:577:13)
    at Compilation.applyPluginsAsync (/Users/nicksrandall/Desktop/dawp-test/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/nicksrandall/Desktop/dawp-test/node_modules/webpack/lib/Compilation.js:572:10)
    at Compilation.next (/Users/nicksrandall/Desktop/dawp-test/node_modules/webpack/node_modules/tapable/lib/Tapable.js:67:11)
    at Compilation.<anonymous> (/Users/nicksrandall/Desktop/dawp-test/node_modules/ng-annotate-webpack-plugin/index.js:34:13)
    at Compilation.applyPluginsAsync (/Users/nicksrandall/Desktop/dawp-test/node_modules/webpack/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.<anonymous> (/Users/nicksrandall/Desktop/dawp-test/node_modules/webpack/lib/Compilation.js:567:9)
    at Compilation.applyPluginsAsync (/Users/nicksrandall/Desktop/dawp-test/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/Users/nicksrandall/Desktop/dawp-test/node_modules/webpack/lib/Compilation.js:563:8)
    at Compilation.applyPluginsAsync (/Users/nicksrandall/Desktop/dawp-test/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.seal (/Users/nicksrandall/Desktop/dawp-test/node_modules/webpack/lib/Compilation.js:525:7)
```

**Comment by jantimon** [comment] 2015-12-02 23:50
Well there is a catch block:
https://github.com/ampedandwired/html-webpack-plugin/blob/master/index.js#L54

Any idea how we could solve this?

**Comment by nicksrandall** [comment] 2015-12-02 23:54
Because it's just a warning and not actually causing any problems, we could just turn it off. See #131

**Comment by jantimon** [comment] 2015-12-03 00:05
Would still be nice to understand the cause of the warning ;)

**Comment by nicksrandall** [comment] 2015-12-03 00:15
I believe that the `finally` method is supposed to return another promise and the callback that is being passed doesn't return anything. We could probably do something like:

```js
.finally(function () {
  callback();
  return null;
});
```

I haven't tested that but I have a hunch that that is where the problem is.

**Comment by jantimon** [comment] 2016-01-11 10:41
Fixed with https://github.com/ampedandwired/html-webpack-plugin/commit/7e4f83b26c4e1b8853098f048df61e16b7d2736d

**Closed by jantimon** 2016-01-11 10:41 UTC
Labels: bug, help wanted
