### ISSUE TITLE
when I use custom-template, hot module does not work.

### ISSUE THREAD

**Issue by honger05** [ampedandwired/html-webpack-plugin#170] opened 2016-01-13 18:13 UTC
Hi,

the setup and built is normal. 

but when I edit some assets, sometimes throw an error as bellow:

punycode.js:530  Uncaught TypeError: __webpack_require__(...) is not a function

**Comment by jantimon** [comment] 2016-01-13 22:17
Could you please provide a minimalistic example and steps to reproduce the issue?

**Comment by honger05** [comment] 2016-01-14 07:56
Here is the [demo repo](https://github.com/honger05/webpack-workflow/tree/master/c07-react/webpack) 

Here is the configuration:

````js

var webpack = require('webpack')
var path = require('path')
var buildPath = path.resolve(__dirname, 'build')
var nodeModulesPath = path.resolve(__dirname, 'node_modules')
var TransferWebpackPlugin = require('transfer-webpack-plugin')
var ExtractTextPlugin = require('extract-text-webpack-plugin')
var HtmlWebpackPlugin = require('html-webpack-plugin')

module.exports = {
  entry: {
    devServer: 'webpack/hot/dev-server',
    index: './src/app/components/index.js',
    detail: './src/app/components/detail.js'
  },
  output: {
    path: buildPath,
    filename: './js/[name].bundle.js',
    chunkFilename: './js/[id].chunk.js'
  },
  devServer: {
    contentBase: 'src/www',
    devtool: 'eval',
    hot: true,
    inline: true,
    port: 3000
  },
  devtool: 'eval',
  resolve: {
    extensions: ['', '.js', '.json', '.coffee']
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),

    new HtmlWebpackPlugin({
      title: 'index',
      filename: 'index.html',
      template: './src/tmpl/index.html',
      chunks: ['index'],
      inject: 'body'
    }),

    new HtmlWebpackPlugin({
      title: 'detail',
      filename: 'detail.html',
      template: './src/tmpl/detail.html',
      chunks: ['detail'],
      inject: 'body'
    }),

    new TransferWebpackPlugin([
      {from: 'www'}
    ], path.resolve(__dirname, "src"))

  ],
  module: {
    loaders: [
      {
        test: /\.less$/,
        loader: 'style!css!less'
      },{
        test: /\.scss$/,
        loader: 'style!css!sass'
      },{
        test: /\.css$/,
        loader: 'style!css'
      },{
        test: /\.(png|jpg)$/,
        loader: 'url?limit=25000'
      },{
        test: /\.ttf$/,
        loader: 'url?limit=100000'
      }
    ]
  }
}

````

**Comment by honger05** [comment] 2016-01-15 02:21
Also， this demo can't use on windows. (win10)

throw an error:

ERROR in ./~/html-webpack-plugin/lib/loader.js!./src/tmpl/detail.html
    Module not found: Error: Cannot resolve module 'lodash' in C:\spm_git_space\webpack-workflow\c07-react\webpack\src\tmpl
     @ ./~/html-webpack-plugin/lib/loader.js!./src/tmpl/detail.html 1:8-25

**Comment by jantimon** [comment] 2016-01-15 16:06
ERROR in ./~/html-webpack-plugin/lib/loader.js!./src/tmpl/detail.html
Module not found: Error: Cannot resolve module 'lodash' in C:\spm_git_space\webpack-workflow\c07-react\webpack\src\tmpl
@ ./~/html-webpack-plugin/lib/loader.js!./src/tmpl/detail.html 1:8-25

should be fixed with 2.6.2 see #170

**Comment by honger05** [comment] 2016-01-16 03:36
Hi, I am sure the HRM does not work on HtmlWebpackPlugin.

only I need is that don't throw error.

I can reload the page on my own.

**Comment by honger05** [comment] 2016-01-16 04:23
2.6.2 occurs anther error.

````js
new HtmlWebpackPlugin({
      title: 'index',
      filename: 'index.html',
      hash: true,
      template: './src/tmpl/index.html',
      chunks: ['index'],
      inject: 'body'
 }),
````

 ERROR in ./~/html-webpack-plugin/lib/loader.js!./src/tmpl/index.html
    Module not found: Error: Cannot resolve module 'C:spm_git_spacewebpack-workflowc07-reactwebpack
    ode_moduleshtml-webpack-plugin
    ode_moduleslodashindex.js' in C:\spm_git_space\webpack-workflow\c07-react\webpack\src\tmpl
     @ ./~/html-webpack-plugin/lib/loader.js!./src/tmpl/index.html 1:8-132

**Comment by jantimon** [comment] 2016-01-16 15:29
The error might come from this file:
https://github.com/ampedandwired/html-webpack-plugin/blob/feature/loaders/lib/loader.js
Unfortunately I don't have a Windows Pc so I can't debug it.

**Comment by honger05** [comment] 2016-01-16 16:19
thanks very much!

Ignore Windows .

**Comment by alex88** [comment] 2016-01-16 22:48
Same here on OSX, this is my base part of the project https://gist.github.com/alex88/869e76e5fcf0717315d2

Others said that since babel 6 you have to use import instead of require

**Comment by jantimon** [comment] 2016-01-17 07:00
Are you sure that this has something to do with the html-webpack-plugin?

**Comment by alex88** [comment] 2016-01-17 07:08
I moved back to 1.7 and it worked just fine, but I made so many changes, I can try again with 2.* and see if that's the issue

**Comment by jantimon** [comment] 2016-01-17 07:11
Sure would love to know if there is an issue

**Comment by alex88** [comment] 2016-01-17 07:49
So I pushed my working explain to https://github.com/alex88/react-redux-boilerplate, run `npm install` and `npm start`, if you change some file you see that live reloading works.
Now try to change `html-webpack-plugin` in `package.json` to `2.6.0` and `npm update`, run again `npm start`.
First load works fine, but trying to hot reload results in a full page reload with that error and even manually reloading doesn't work anymore

**Comment by jantimon** [comment] 2016-01-17 14:11
Thanks alex I'll look into it

**Comment by jantimon** [comment] 2016-01-19 08:55
@alex88 @honger05 this should have been fixed with https://github.com/ampedandwired/html-webpack-plugin/pull/178 which is 2.6.4 - could you please give it another try?

**Closed** 2016-01-19 08:55 UTC

**Comment by alex88** [comment] 2016-01-19 17:59
@jantimon yup it works fine now! Thanks a lot!
