### ISSUE TITLE
Unhandled rejection Error: Invalid arguments: 'delay'

### ISSUE THREAD

**Issue by shprink** [ampedandwired/html-webpack-plugin#65] opened 2015-06-29 14:40 UTC
This error is pretty new and happens with either v1.4.x or 1.5.x. It seems to be related to bluebird (they released a new version 15 days ago), maybe you should fix the bluebird version.

Till then the Webpack watch is broken.

```
Unhandled rejection Error: Invalid arguments: 'delay'
    at NodeWatchFileSystem.watch (/Users/shprink/Sites/bixev/react2pics/node_modules/webpack/lib/node/NodeWatchFileSystem.js:29:9)
    at Watching.watch (/Users/shprink/Sites/bixev/react2pics/node_modules/webpack/lib/Compiler.js:86:47)
    at Watching._done (/Users/shprink/Sites/bixev/react2pics/node_modules/webpack/lib/Compiler.js:82:8)
    at Watching.<anonymous> (/Users/shprink/Sites/bixev/react2pics/node_modules/webpack/lib/Compiler.js:60:18)
    at Tapable.emitRecords (/Users/shprink/Sites/bixev/react2pics/node_modules/webpack/lib/Compiler.js:279:37)
    at Watching.<anonymous> (/Users/shprink/Sites/bixev/react2pics/node_modules/webpack/lib/Compiler.js:57:19)
    at /Users/shprink/Sites/bixev/react2pics/node_modules/webpack/lib/Compiler.js:272:11
    at Tapable.applyPluginsAsync (/Users/shprink/Sites/bixev/react2pics/node_modules/webpack/node_modules/tapable/lib/Tapable.js:60:69)
    at Tapable.afterEmit (/Users/shprink/Sites/bixev/react2pics/node_modules/webpack/lib/Compiler.js:269:8)
    at Tapable.<anonymous> (/Users/shprink/Sites/bixev/react2pics/node_modules/webpack/lib/Compiler.js:264:14)
    at done (/Users/shprink/Sites/bixev/react2pics/node_modules/webpack/node_modules/async/lib/async.js:132:19)
    at /Users/shprink/Sites/bixev/react2pics/node_modules/webpack/node_modules/async/lib/async.js:32:16
    at MemoryFileSystem.writeFile (/Users/shprink/Sites/bixev/react2pics/node_modules/webpack-dev-server/node_modules/webpack-dev-middleware/node_modules/memory-fs/lib/MemoryFileSystem.js:224:9)
    at Tapable.writeOut (/Users/shprink/Sites/bixev/react2pics/node_modules/webpack/lib/Compiler.js:258:27)
    at Tapable.<anonymous> (/Users/shprink/Sites/bixev/react2pics/node_modules/webpack/lib/Compiler.js:244:20)
    at /Users/shprink/Sites/bixev/react2pics/node_modules/webpack/node_modules/async/lib/async.js:122:13
    at _each (/Users/shprink/Sites/bixev/react2pics/node_modules/webpack/node_modules/async/lib/async.js:46:13)
    at Object.async.each (/Users/shprink/Sites/bixev/react2pics/node_modules/webpack/node_modules/async/lib/async.js:121:9)
    at Tapable.emitFiles (/Users/shprink/Sites/bixev/react2pics/node_modules/webpack/lib/Compiler.js:233:20)
    at MemoryFileSystem.(anonymous function) [as mkdirp] (/Users/shprink/Sites/bixev/react2pics/node_modules/webpack-dev-server/node_modules/webpack-dev-middleware/node_modules/memory-fs/lib/MemoryFileSystem.js:197:10)
    at Tapable.<anonymous> (/Users/shprink/Sites/bixev/react2pics/node_modules/webpack/lib/Compiler.js:227:25)
    at Tapable.next (/Users/shprink/Sites/bixev/react2pics/node_modules/webpack/node_modules/tapable/lib/Tapable.js:67:11)
    at Tapable.<anonymous> (/Users/shprink/Sites/bixev/react2pics/node_modules/webpack/lib/ProgressPlugin.js:73:4)
    at Tapable.next (/Users/shprink/Sites/bixev/react2pics/node_modules/webpack/node_modules/tapable/lib/Tapable.js:69:14)
    at Object.finallyHandler (/Users/shprink/Sites/bixev/react2pics/node_modules/html-webpack-plugin/node_modules/bluebird/js/main/finally.js:40:23)
    at Object.tryCatcher (/Users/shprink/Sites/bixev/react2pics/node_modules/html-webpack-plugin/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Users/shprink/Sites/bixev/react2pics/node_modules/html-webpack-plugin/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/Users/shprink/Sites/bixev/react2pics/node_modules/html-webpack-plugin/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromises (/Users/shprink/Sites/bixev/react2pics/node_modules/html-webpack-plugin/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/Users/shprink/Sites/bixev/react2pics/node_modules/html-webpack-plugin/node_modules/bluebird/js/main/async.js:182:16)
    at Async._drainQueues (/Users/shprink/Sites/bixev/react2pics/node_modules/html-webpack-plugin/node_modules/bluebird/js/main/async.js:192:10)
    at Async.drainQueues (/Users/shprink/Sites/bixev/react2pics/node_modules/html-webpack-plugin/node_modules/bluebird/js/main/async.js:15:14)
    at process._tickCallback (node.js:419:13)
```

**Comment by jantimon** [comment] 2015-06-29 15:00
Can it be fixed by setting the bluebird version back down?

**Comment by jantimon** [comment] 2015-07-02 22:32
Can't reproduce

**Closed by jantimon** 2015-07-02 22:32 UTC

**Comment by Elxx** [comment] 2015-07-06 15:53
@shprink: I ran into this error using an old version of webpack (1.7.2), updating it to 1.10.1 fixed it.
