### ISSUE TITLE
js&css cannot be injected into the HTML file @version 2

### ISSUE THREAD

**Issue by xiaoyunchen** [ampedandwired/html-webpack-plugin#135] opened 2015-12-08 08:05 UTC
this is my config:
```javascript
new HtmlWebpackPlugin({						
    		favicon:'./src/img/favicon.ico',
			filename:'/view/index.html',	
			template:'./src/view/index.html',	
			inject:true,
			hash:true,	
			minify:{	
				removeComments:true,	
				collapseWhitespace:false	
			}
		})
```
the same config file,If I use the version 1.7,it works!
But when I update to version 2,js&css cannot be injected into the HTML file,and even more, collapseWhitespace option in the minify option is not works neither.please check it and thanks.

**Comment by jantimon** [comment] 2015-12-13 09:13
Is this a duplicate of https://github.com/ampedandwired/html-webpack-plugin/issues/128 ?

**Comment by xiaoyunchen** [comment] 2015-12-13 13:10
I checked the #128 issue before submit this one,and it's not the same.
I don't use any js template like jade but only plain HTML.
And I  also attach this attribute removeOptionalTags=false for the html-loader,but the problems still exist.

So the new version is worked in your project?Or I missed something important？

**Comment by jantimon** [comment] 2016-01-08 08:46
@xiaoyunchen could you please try if it works now?

**Comment by xiaoyunchen** [comment] 2016-01-14 07:38
SORRY!Reply so late.
And I checked this problem with version 2.6.1,the js&css files can be injected into the HTML file but another problem comes.
When I use html-webpack-plugin and UglifyJsPlugin (minify and ungify my JS files),the HTML looks like below:
![qq 20160114152954](https://cloud.githubusercontent.com/assets/13519615/12318235/bf5db7e2-bad3-11e5-8d33-14b9b924e08d.png)
two head tags!

And this is part of my webpack config file:
```javascript

plugins:[
    	new webpack.ProvidePlugin({	
            $: 'jquery'
        }),
    	new ExtractTextPlugin("css/[name].css"),
    	new webpack.optimize.UglifyJsPlugin({	
		    compress: {
		        warnings: false
		    },
		    except: ['$super', '$', 'exports', 'require']	
		}),
    	new HtmlWebpackPlugin({						
    		favicon:'./src/img/favicon.ico', 
			filename:'/view/index.html',	
			template:'./src/view/index.html',	
			inject:true,	
			hash:true,	
			minify:{	
				removeComments:true,	
				collapseWhitespace:true	
			}
		})
    ]

```

and thx!

**Comment by jantimon** [comment] 2016-01-14 08:54
Oh thanks for the bug report could you please show me the source of ./src/view/index.html ?

**Comment by xiaoyunchen** [comment] 2016-01-14 08:56
Yes,it's so simple:
```javascript
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Index主页</title>
		<meta name="author" content="https://github.com/xiaoyunchen/webpack"/>
		<meta name="date" content="2015-12-3"/>
		<meta name="description" content="for test"/>
		<!--
        	comments here
        -->
	</head>
	<body>
		<p>
			<button id="btn">Add</button>
		</p>
		<!--
        	another comment and should be removed
        -->
	</body>
</html>

```

**Comment by jantimon** [comment] 2016-01-14 09:09
This seems to be an html-loader bug
```html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Example template</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
  <img src="logo.png">
</body>
</html>
```

Now if you add the 
Is turned into:

```html
<!DOCTYPE html><html lang=en><head><meta charset=utf-8><title>Example template</title><meta name=viewport content="width=device-width,initial-scale=1"><body><img src=0714810ae3fb211173e2964249507195.png>
```

As you can see it removes ALL closing html tags.

**Comment by xiaoyunchen** [comment] 2016-01-14 09:12
Yes,without the ending tags of html/body/head

**Comment by jantimon** [comment] 2016-01-14 09:42
There is already an issue for that: https://github.com/webpack/html-loader/issues/40

**Comment by jantimon** [comment] 2016-01-14 09:45
For now you can disable `removeOptionalTags` in your html loader configuration:
```js
  { test: /\.html$/, loader: 'html-loader?-removeOptionalTags' },
```

**Comment by xiaoyunchen** [comment] 2016-01-14 09:46
OK,Thx for that and I will try this

**Closed** 2016-01-19 13:55 UTC
Labels: bug

**Comment by xiaoyunchen** [comment] 2016-01-25 09:38
the CSS cannot be injected either even disable removeOptionalTags option
but the JS file works normally

**Comment by jantimon** [comment] 2016-01-25 15:10
Please see the examples folder :)
